# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from dnbr_tasks import calculate_dnbr as calculate_dnbr
from dnbr_tasks import combine_dnbr_layers as combine_dnbr_layers
from dnbr_tasks import count_burned_area_ha as count_burned_area_ha
from dnbr_tasks import count_high_severity_area_ha as count_high_severity_area_ha
from dnbr_tasks import count_mean_dnbr as count_mean_dnbr
from dnbr_tasks import count_post_images as count_post_images
from dnbr_tasks import count_pre_images as count_pre_images
from dnbr_tasks import create_dnbr_layer as create_dnbr_layer
from dnbr_tasks import create_styled_overlay_layer as create_styled_overlay_layer
from dnbr_tasks import extract_fire_date as extract_fire_date
from dnbr_tasks import format_area_ha as format_area_ha
from dnbr_tasks import format_image_count as format_image_count
from dnbr_tasks import format_mean_dnbr as format_mean_dnbr
from dnbr_tasks import format_optional_name as format_optional_name
from dnbr_tasks import load_fire_event_from_er as load_fire_event_from_er
from dnbr_tasks import set_overlay_group_name as set_overlay_group_name
from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.io import (
    get_spatial_features_group as get_spatial_features_group,
)
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.io import set_er_connection as set_er_connection
from ecoscope.platform.tasks.io import set_gee_connection as set_gee_connection
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import (
    create_text_widget_single_view as create_text_widget_single_view,
)
from ecoscope.platform.tasks.results import draw_ecomap as draw_ecomap
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.results import set_base_maps as set_base_maps
from ecoscope.platform.tasks.skip import (
    any_dependency_is_empty_string as any_dependency_is_empty_string,
)
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope.platform.tasks.skip import never as never
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    er_connection = (
        task(set_er_connection)
        .validate()
        .set_task_instance_id("er_connection")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("er_connection") or {}))
        .call()
    )

    gee_connection = (
        task(set_gee_connection)
        .validate()
        .set_task_instance_id("gee_connection")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("gee_connection") or {}))
        .call()
    )

    fire_event = (
        task(load_fire_event_from_er)
        .validate()
        .set_task_instance_id("fire_event")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(client=er_connection, **(params.get("fire_event") or {}))
        .call()
    )

    fire_date = (
        task(extract_fire_date)
        .validate()
        .set_task_instance_id("fire_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(event_gdf=fire_event, **(params.get("fire_date") or {}))
        .call()
    )

    overlay_name = (
        task(set_overlay_group_name)
        .validate()
        .set_task_instance_id("overlay_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("overlay_name") or {}))
        .call()
    )

    overlay_features = (
        task(get_spatial_features_group)
        .validate()
        .set_task_instance_id("overlay_features")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_is_empty_string,
            ],
            unpack_depth=1,
        )
        .partial(
            client=er_connection,
            spatial_features_group_name=overlay_name,
            **(params.get("overlay_features") or {}),
        )
        .call()
    )

    base_maps = (
        task(set_base_maps)
        .validate()
        .set_task_instance_id("base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("base_maps") or {}))
        .call()
    )

    dnbr_result = (
        task(calculate_dnbr)
        .validate()
        .set_task_instance_id("dnbr_result")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            client=gee_connection,
            roi=fire_event,
            fire_date=fire_date,
            **(params.get("dnbr_result") or {}),
        )
        .call()
    )

    dnbr_layer = (
        task(create_dnbr_layer)
        .validate()
        .set_task_instance_id("dnbr_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=dnbr_result, **(params.get("dnbr_layer") or {}))
        .call()
    )

    perimeter_layer = (
        task(create_styled_overlay_layer)
        .validate()
        .set_task_instance_id("perimeter_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=fire_event, **(params.get("perimeter_layer") or {}))
        .call()
    )

    overlay_layer = (
        task(create_styled_overlay_layer)
        .validate()
        .set_task_instance_id("overlay_layer")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=overlay_features, **(params.get("overlay_layer") or {}))
        .call()
    )

    combined_layers = (
        task(combine_dnbr_layers)
        .validate()
        .set_task_instance_id("combined_layers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
            ],
            unpack_depth=1,
        )
        .partial(
            dnbr_layer=dnbr_layer,
            perimeter_layer=perimeter_layer,
            overlay_layer=overlay_layer,
            **(params.get("combined_layers") or {}),
        )
        .call()
    )

    severity_map = (
        task(draw_ecomap)
        .validate()
        .set_task_instance_id("severity_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title=None,
            tile_layers=base_maps,
            geo_layers=combined_layers,
            north_arrow_style={"placement": "top-left"},
            legend_style={"title": "Fire Severity", "placement": "bottom-right"},
            static=False,
            max_zoom=20,
            **(params.get("severity_map") or {}),
        )
        .call()
    )

    severity_map_url = (
        task(persist_text)
        .validate()
        .set_task_instance_id("severity_map_url")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            filename_suffix="dnbr",
            text=severity_map,
            **(params.get("severity_map_url") or {}),
        )
        .call()
    )

    map_widget = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("map_widget")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Fire Severity Map",
            data=severity_map_url,
            **(params.get("map_widget") or {}),
        )
        .call()
    )

    burned_area_ha = (
        task(count_burned_area_ha)
        .validate()
        .set_task_instance_id("burned_area_ha")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=dnbr_result, **(params.get("burned_area_ha") or {}))
        .call()
    )

    burned_area_fmt = (
        task(format_area_ha)
        .validate()
        .set_task_instance_id("burned_area_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(area_ha=burned_area_ha, **(params.get("burned_area_fmt") or {}))
        .call()
    )

    widget_burned = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_burned")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Burned", data=burned_area_fmt, **(params.get("widget_burned") or {})
        )
        .call()
    )

    high_severity_ha = (
        task(count_high_severity_area_ha)
        .validate()
        .set_task_instance_id("high_severity_ha")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=dnbr_result, **(params.get("high_severity_ha") or {}))
        .call()
    )

    high_severity_fmt = (
        task(format_area_ha)
        .validate()
        .set_task_instance_id("high_severity_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(area_ha=high_severity_ha, **(params.get("high_severity_fmt") or {}))
        .call()
    )

    widget_high_severity = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_high_severity")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="High Sev",
            data=high_severity_fmt,
            **(params.get("widget_high_severity") or {}),
        )
        .call()
    )

    widget_fire_date = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_fire_date")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(title="Date", data=fire_date, **(params.get("widget_fire_date") or {}))
        .call()
    )

    overlay_display_name = (
        task(format_optional_name)
        .validate()
        .set_task_instance_id("overlay_display_name")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[],
            unpack_depth=1,
        )
        .partial(name=overlay_name, **(params.get("overlay_display_name") or {}))
        .call()
    )

    widget_overlay = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_overlay")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Overlay",
            data=overlay_display_name,
            **(params.get("widget_overlay") or {}),
        )
        .call()
    )

    mean_dnbr = (
        task(count_mean_dnbr)
        .validate()
        .set_task_instance_id("mean_dnbr")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=dnbr_result, **(params.get("mean_dnbr") or {}))
        .call()
    )

    mean_dnbr_fmt = (
        task(format_mean_dnbr)
        .validate()
        .set_task_instance_id("mean_dnbr_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(dnbr_value=mean_dnbr, **(params.get("mean_dnbr_fmt") or {}))
        .call()
    )

    widget_mean_dnbr = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_mean_dnbr")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="dNBR Avg",
            data=mean_dnbr_fmt,
            **(params.get("widget_mean_dnbr") or {}),
        )
        .call()
    )

    pre_scenes = (
        task(count_pre_images)
        .validate()
        .set_task_instance_id("pre_scenes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=dnbr_result, **(params.get("pre_scenes") or {}))
        .call()
    )

    pre_scenes_fmt = (
        task(format_image_count)
        .validate()
        .set_task_instance_id("pre_scenes_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(count=pre_scenes, **(params.get("pre_scenes_fmt") or {}))
        .call()
    )

    widget_pre_scenes = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_pre_scenes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Pre Imgs",
            data=pre_scenes_fmt,
            **(params.get("widget_pre_scenes") or {}),
        )
        .call()
    )

    post_scenes = (
        task(count_post_images)
        .validate()
        .set_task_instance_id("post_scenes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(geodataframe=dnbr_result, **(params.get("post_scenes") or {}))
        .call()
    )

    post_scenes_fmt = (
        task(format_image_count)
        .validate()
        .set_task_instance_id("post_scenes_fmt")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(count=post_scenes, **(params.get("post_scenes_fmt") or {}))
        .call()
    )

    widget_post_scenes = (
        task(create_text_widget_single_view)
        .validate()
        .set_task_instance_id("widget_post_scenes")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Post Imgs",
            data=post_scenes_fmt,
            **(params.get("widget_post_scenes") or {}),
        )
        .call()
    )

    dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=[
                widget_burned,
                widget_high_severity,
                widget_fire_date,
                widget_overlay,
                widget_mean_dnbr,
                widget_pre_scenes,
                widget_post_scenes,
                map_widget,
            ],
            time_range=None,
            **(params.get("dashboard") or {}),
        )
        .call()
    )

    return dashboard
